version: "3.8"
services:
  test:
    build: .
    stdin_open: true
    tty: true
    container_name: node-container
    volumes:
      - type: bind
        source: ../
        target: /home/developer/jsadsl
