version: "3.8"
services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    image: jsadsl_image
    stdin_open: true
    tty: true
    container_name: jsadsl_container
    volumes:
      - type: volume
        source: jsadsl_volume
        target: /home/developer/app

volumes:
  jsadsl_volume: